CREATE TABLE IF NOT EXISTS users (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Username VARCHAR(30) UNIQUE,
    Password TEXT
);
CREATE TABLE IF NOT EXISTS sessions (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Key TEXT,
    UserId INTEGER,
    FOREIGN KEY (UserId) REFERENCES users(Id)
);